### ISSUE TITLE
Corrigir a função parseStringAsArray para quando 'techs' não for passado na requisição

### ISSUE THREAD

**Issue by vs0uz4** [rocketseat-education/semana-omnistack-10#3]
Se por acaso o usuário não definir **techs** ao acessar o backend (API), o servidor irá retornar um erro, dizendo não poder executar o método 'split' para algo indefinido.

> UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined

O erro ocorre na linha de código de número 2 da função.
https://github.com/Rocketseat/semana-omnistack-10/blob/397b89a4631e5f36756367847e9acbf53402ba54/backend/src/utils/parseStringAsArray.js#L2

**Comment by jpedroschmitz** [comment]
Merged on #4
